apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
{{- if .Values.nginxConfOverride }}
{{ tpl .Values.nginxConfOverride . | indent 4 }}
{{- else }}
{{ .Files.Get "files/nginx/nginx.conf" | indent 4 }}
{{- end }}
