apiVersion: v1
kind: ConfigMap
metadata:
  name: cat-website-nginx-config
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://cat-website-app:{{ .Values.service.appPort }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
